### ISSUE TITLE
ssh server not running

### ISSUE THREAD

**Issue by benaka47** [CloudSlang/CloudSlang-Docker-Image#10]
It seems that the image was buit without the the starting script "start-cslang.sh", the ssh server is not started.

**Comment by levice14** [comment]
thanks @benaka47 for the feedback,

it seems to me that the `start-cslang.sh` is found in the latest image: **cloudslang/cloudslang-dev:latest**
I was working with the following commmands on Ubuntu machine:

``` bash
docker run -it -p 32165:22  cloudslang/cloudslang-dev
ssh -p 32165 root@localhost # pass: cslang
```

can you please conform the behavior?
also adding @mbettan

**Comment by levice14** [comment]
also be sure not to confuse [the old lightweight image](https://hub.docker.com/r/cloudslang/cloudslang/~/dockerfile/) with the [new DEV image](https://hub.docker.com/r/cloudslang/cloudslang-dev/~/dockerfile/) which contains advanced feature like ssh server, Atom etc.

we have an [issue](https://github.com/CloudSlang/docs/issues/119) on considering moving to DEV image

**Comment by benaka47** [comment]
thank you @Bonczidai, in fact I was using the cloudslang/cloudslang image, cloudslang/cloudslang-dev worked as expected
