### ISSUE TITLE
Latest Docker image uses the outdated 0.9.1

### ISSUE THREAD

**Issue by lirantal** [CloudSlang/CloudSlang-Docker-Image#13]
Hey,

The official repository at https://hub.docker.com/r/cloudslang/cloudslang/ uses CS + Content release from the 0.9.1 version which is from December 2015.

How about we upgrade to the Dockerfile to 0.9.50?

**Comment by levice14** [comment]
:+1:

**Comment by gituser173** [comment]
I think this is already done here: https://github.com/CloudSlang/CloudSlang-Docker-Image/pull/12
