### ISSUE TITLE
What's the difference between the cloudslang container and cloudslang-dev?

### ISSUE THREAD

**Issue by lirantal** [CloudSlang/CloudSlang-Docker-Image#15]
Hi,

I noticed there are 2 repositories for containers:
- CloudSlang official: https://hub.docker.com/r/cloudslang/cloudslang
- CloudSlang-dev: https://hub.docker.com/r/cloudslang/cloudslang-dev

Where the Dockerfile on the dev container is much richer (https://hub.docker.com/r/cloudslang/cloudslang-dev/~/dockerfile/) - what is the difference and what are the use cases to use each of them?

**Comment by levice14** [comment]
hi @lirantal ,

the dev image was recently contributed by @mbettan 

it contains preconfigured dev tools like: Python, Vim, Emacs, Atom, Git, ssh server etc.

the PR: https://github.com/CloudSlang/CloudSlang-Docker-Image/pull/9
the open issue to document it: https://github.com/CloudSlang/docs/issues/119

btw, WDYT about this image, do you see any improvement possibilities here?

**Comment by mbettan** [comment]
FYI - I have a made an online video https://youtu.be/jRx-hR_Dnck 
It shows how you can use Dev Container image

**Comment by levice14** [comment]
thanks @mbettan - this is cool :+1: I think it would be :100: with voice + showing all the feature of the image -- in that case we should publish it on our Youtube channel for sure

also adding @SamMarkowitz , @gituser173 to this thread

**Comment by lirantal** [comment]
I'll need to review the comments + video + docker image (which I didn't yet) and get back to you on this topic :)

**Comment by mbettan** [comment]
@SamMarkowitz do you want to record your voice?

**Comment by SamMarkowitz** [comment]
@mbettan Sure, I can do the voice-over if you'd like. First, let's give one last chance for people to make comments and suggestions. Do you have a script or some notes on what you want to be said?
